### ISSUE TITLE
Not using any prefix?

### ISSUE THREAD

**Issue by benp** [Workshape/icon-font-generator#19]
Is it possible do completely do away with the prefix? I tried different options but no luck so far. thanks.

**Comment by tancredi** [comment]
Not so easy with the current implementation, though you can always provide it a different css template (just copy the one on the repo and remove the prefix from it - it's a bit hacky but it should do) - otherwise you can generate CSS separately by using the JSON map.

It's something that we could implement to make it easier although I don't see many use-cases - why are you dropping the prefixes, if I may ask?

**Comment by plamf** [comment]
I'm having the same issue.
Our tag needs to be the same as our prefix. If can't omit the prefix, my css selectors will be "myicons-myicons-hourglass", but I want "myicons-hourglass"
