### ISSUE TITLE
Icon vertical heights off between windows and mac (both chrome) - Fix Vertical Metrics

### ISSUE THREAD

**Issue by johnjjung** [Workshape/icon-font-generator#34]
So according to this post and several hours of researching:

https://stackoverflow.com/questions/10044130/custom-fonts-with-differrent-vertical-metrics-between-oss

It seems like this issue is happening because of whitespace above the icons generated.

I tried using configs to adjust heights `--fontHeight=0px` etc... but no dice.

Apparently everyone goes to https://www.fontsquirrel.com/tools/webfont-generator

Then fixes the vertical heights there, but there's gotta be a way to fix this so it's cross OS compatible!

**Comment by johnjjung** [comment]
@tancredi https://github.com/fontello/svg2ttf/issues/48

Looks like this is a known issue

**Comment by johnjjung** [comment]
It still seems like an issue from the lib itself, I get that icon-font-generator is a wrapper around webfonts-generator. In webfonts-generator I think it can be fixed where it calls [svg2ttf](https://github.com/sunflowerdeath/webfonts-generator/blob/3f52b4e36c9541bea7564bdb9aa7a82efbac815a/src/generateFonts.js#L66) I'm sure there's ways to adjust the ascent or descent or try to center the vertical spacing

**Comment by tancredi** [comment]
@johnjjung thanks for reporting. Seems like the last reply on that issue was in 2016 - worth bumping with an update? I'm not too versed on font rendering (also I've always been using this library with square icons and same sizes so I did not encounter this issue).

**Comment by tancredi** [comment]
Otherwise if you have an idea for a fix on our `icon-font-generator` level please suggest @johnjjung

**Comment by mOveoStudio** [comment]
I think this problem is still here (correct me if I'm wrong).

When you use icon-font-generator you always have a blank space above icons as you can see here:
![icon-generator-blank](https://user-images.githubusercontent.com/2760450/66315420-1016e900-e916-11e9-81ec-fc275292fceb.jpg)

I fixed it by adding a line-height on the base tag element. I don't know if it's the best way to go, but it seems working well. Here is an extract of the hbs template edited:
```
{{ baseTag }}[class^="{{classPrefix}}"],
{{ baseTag }}[class*=" {{classPrefix}}"]{
    font: normal normal normal 14px/1 {{ fontName }};
    font-size: inherit;
}
```

**Comment by vdolbilov** [comment]
Can confirm this issue still exists, and that applying the patch at https://github.com/fontello/svg2ttf/pull/82 to `node_modules/icon-font-generator/node_modules/svg2tff` seems to fix the problem.

**Comment by geochanto** [comment]
Not sure why this is closed. Should be reopened imho.

Can confirm also running into this issue. Even though SVG's don't have spacing, icon font glyphs that get generated have extra space on top. Mac ignores this space, but PC does not, so we end up with inconsistent positioning on Mac vs PC that's impossible to fix with CSS since there are no OS-specific media queries.

Can confirm fontello does not add extra space using their online tool.

**Comment by uchihamalolan** [comment]
This might be because windows uses `winAscent` and `winDescent` for calculating ascent and descent values. 

I created a seperate PR to include this feature
https://github.com/fontello/svg2ttf/issues/95

And the solution for it. 
https://github.com/fontello/svg2ttf/pull/96

If done, then one can simply pass an option `useTypoMetrics: true` and we'll make sure to set the font to use typoMetrics by default and windows will adhere to that.

Hope I was clear in explaining.

**Comment by puzrin** [comment]
I've updated svg2ttf, now desired bit is set.
